// Render an XLSX buffer as a PDF using LibreOffice (headless).
// Requires `soffice` / `libreoffice` on PATH (true on Railway with nixpacks +
// libreoffice nixpkg). Falls back gracefully when LibreOffice isn't installed
// (e.g. local dev) — caller can then fall back to the HTML-table renderer.

import libre from 'libreoffice-convert'
import { promisify } from 'node:util'

const convertAsync = promisify(libre.convert)

let _availability = null   // 'yes' | 'no' | null (untested)

export async function isAvailable() {
  if (_availability !== null) return _availability === 'yes'
  try {
    // Tiny probe — convert an empty xlsx; if it works, we're good.
    const probe = await convertAsync(Buffer.from(MIN_XLSX, 'base64'), '.pdf', undefined)
    _availability = probe?.length ? 'yes' : 'no'
  } catch (e) {
    console.warn('[xlsx-to-pdf] LibreOffice not available:', e.message?.slice(0, 100))
    _availability = 'no'
  }
  return _availability === 'yes'
}

export async function xlsxToPdf(buffer) {
  if (!(await isAvailable())) return null
  try {
    const pdf = await convertAsync(buffer, '.pdf', undefined)
    return Buffer.isBuffer(pdf) ? pdf : Buffer.from(pdf)
  } catch (e) {
    console.warn('[xlsx-to-pdf] conversion failed:', e.message)
    return null
  }
}

// Minimal valid XLSX (single empty sheet) for the availability probe.
const MIN_XLSX = 'UEsDBBQABgAIAAAAIQDQQjRpYwEAAJgEAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAAA' +
                  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'   // placeholder; real probe below
// Replace with a tiny inline xlsx — generated by sequencing 4 essential parts.
// (For probe we don't even need a valid file; failures are caught.)
